# Generated by Django 5.1.4 on 2024-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_name', models.CharField(max_length=50)),
                ('my_email', models.EmailField(max_length=254)),
                ('my_contact', models.IntegerField()),
                ('my_image', models.FileField(upload_to='image/')),
                ('my_resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
