# Generated by Django 5.1.4 on 2024-12-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='my_contact',
            new_name='stu_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='my_email',
            new_name='stu_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='my_image',
            new_name='stu_image',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='my_name',
            new_name='stu_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='my_resume',
            new_name='stu_resume',
        ),
    ]
